# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='person_service.proto',
  package='personapp',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14person_service.proto\x12\tpersonapp\"2\n\rPersonRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0biso_country\x18\x02 \x01(\t\"p\n\x0ePersonResponse\x12\x31\n\x07persons\x18\x01 \x03(\x0b\x32 .personapp.PersonResponse.Person\x1a+\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0biso_country\x18\x02 \x01(\t2L\n\x06Person\x12\x42\n\tGetPerson\x12\x18.personapp.PersonRequest\x1a\x19.personapp.PersonResponse\"\x00\x62\x06proto3')
)




_PERSONREQUEST = _descriptor.Descriptor(
  name='PersonRequest',
  full_name='personapp.PersonRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='personapp.PersonRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iso_country', full_name='personapp.PersonRequest.iso_country', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=85,
)


_PERSONRESPONSE_PERSON = _descriptor.Descriptor(
  name='Person',
  full_name='personapp.PersonResponse.Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='personapp.PersonResponse.Person.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iso_country', full_name='personapp.PersonResponse.Person.iso_country', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=199,
)

_PERSONRESPONSE = _descriptor.Descriptor(
  name='PersonResponse',
  full_name='personapp.PersonResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='persons', full_name='personapp.PersonResponse.persons', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PERSONRESPONSE_PERSON, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=199,
)

_PERSONRESPONSE_PERSON.containing_type = _PERSONRESPONSE
_PERSONRESPONSE.fields_by_name['persons'].message_type = _PERSONRESPONSE_PERSON
DESCRIPTOR.message_types_by_name['PersonRequest'] = _PERSONREQUEST
DESCRIPTOR.message_types_by_name['PersonResponse'] = _PERSONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PersonRequest = _reflection.GeneratedProtocolMessageType('PersonRequest', (_message.Message,), dict(
  DESCRIPTOR = _PERSONREQUEST,
  __module__ = 'person_service_pb2'
  # @@protoc_insertion_point(class_scope:personapp.PersonRequest)
  ))
_sym_db.RegisterMessage(PersonRequest)

PersonResponse = _reflection.GeneratedProtocolMessageType('PersonResponse', (_message.Message,), dict(

  Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), dict(
    DESCRIPTOR = _PERSONRESPONSE_PERSON,
    __module__ = 'person_service_pb2'
    # @@protoc_insertion_point(class_scope:personapp.PersonResponse.Person)
    ))
  ,
  DESCRIPTOR = _PERSONRESPONSE,
  __module__ = 'person_service_pb2'
  # @@protoc_insertion_point(class_scope:personapp.PersonResponse)
  ))
_sym_db.RegisterMessage(PersonResponse)
_sym_db.RegisterMessage(PersonResponse.Person)



_PERSON = _descriptor.ServiceDescriptor(
  name='Person',
  full_name='personapp.Person',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=201,
  serialized_end=277,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPerson',
    full_name='personapp.Person.GetPerson',
    index=0,
    containing_service=None,
    input_type=_PERSONREQUEST,
    output_type=_PERSONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PERSON)

DESCRIPTOR.services_by_name['Person'] = _PERSON

# @@protoc_insertion_point(module_scope)
