version: '3'

services:
        
    db:
        build: ./db
        #image: postgres:latest
        
        volumes:
            - dbdata:/var/lib/dbdata
        networks:
            - backend
        ports:
            - "5432:5432"

    
    flask-svc:
        restart: always
        build: ./flask-service
        networks:
            - backend
        depends_on:
            - db 
            #This causes the service not to be started until the db is up.
        ports:
            - "5000:5000"

            
    grpc-svc:
        restart: always
        build: ./grpc-service
        networks:
            - backend
        depends_on:
            - db
        ports:
            - "50051:50051"
    
    
    web-react:
        restart: always
        build: ./web-react-app
        depends_on:
            - db
        #It doesn't really depend on the db... this is just to stop the addition of this image from messing up the start order of the others.
        networks:
            - frontend
        ports:
            - "4000:4000"

networks:
    backend:
        
    frontend:
        
            
volumes:
  dbdata:
      
      

      