CREATE DATABASE postgres WITH ENCODING 'UTF8';


CREATE SCHEMA app_dev;
CREATE SCHEMA app_tst;
CREATE SCHEMA app_prd;

CREATE USER flasksvcuser ENCRYPTED PASSWORD 'flasksvcpw1234' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE USER grpcsvcuser ENCRYPTED PASSWORD 'grpcsvcpw1234' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE USER grpcclientuser ENCRYPTED PASSWORD 'grpcclientpw1234' NOSUPERUSER NOCREATEDB NOCREATEROLE;

GRANT ALL PRIVILEGES ON persondb TO flasksvcuser;
GRANT ALL PRIVILEGES ON persondb TO grpcsvcuser;
GRANT SELECT ON ALL TABLES IN SCHEMA appschema TO grpcclientuser; 




